# Generated by Django 3.1.4 on 2021-03-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='gender',
            field=models.CharField(default='none', max_length=500),
        ),
    ]
