# Generated by Django 3.1.3 on 2021-02-08 10:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_user', '__first__'),
        ('question', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('compete_slug', models.CharField(default='no slug', max_length=500)),
                ('compete_level', models.CharField(default='simple', max_length=500)),
                ('compete_category', models.CharField(max_length=500)),
                ('duration', models.CharField(max_length=500)),
                ('status', models.BooleanField(default=False)),
                ('audience', models.CharField(default='private', max_length=500)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compete_id', models.CharField(default='none', max_length=100)),
                ('compete_title', models.CharField(default='none', max_length=100)),
                ('compete_type', models.CharField(default='none', max_length=100)),
                ('compete_slug', models.CharField(default='none', max_length=100)),
                ('answers', models.CharField(default='none', max_length=100)),
                ('response_theory', models.TextField(default='none')),
                ('score', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('percentage', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='CompeteQuestionConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('compete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compete.compete')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question')),
            ],
        ),
        migrations.AddField(
            model_name='compete',
            name='questions',
            field=models.ManyToManyField(through='compete.CompeteQuestionConnector', to='question.Question'),
        ),
    ]
